In [ ]:
"""
What are the different data structures used in Tensorflow?. Give some examplesc
"""
"""
In TensorFlow, there are several data structures used for representing and manipulating data. Here are the main ones along with examples:

Tensors: Tensors are multi-dimensional arrays used to store and compute numerical data. They can represent scalars, vectors, matrices, or higher-dimensional arrays. For example, a tensor can store pixel values of an image or feature vectors in a dataset.

Variables: Variables are mutable tensors that hold values during computation. They are often used to store model parameters that need to be optimized, such as weights and biases in neural networks. For instance, in a linear regression model, a variable can represent the slope and intercept of the regression line.

Constants: Constants are tensors with fixed values that remain unchanged throughout the computation. They are typically used to store hyperparameters or other fixed values. An example of a constant can be the number of classes in a classification problem.

Placeholders: Placeholders act as input nodes in the computational graph and are used for dynamic data feeding during execution. They allow data to be supplied later during runtime. For example, a placeholder can be used to feed batches of images or sequences of different lengths into a model.

Sparse Tensors: Sparse tensors are designed to efficiently represent and process tensors with a large number of zero or sparse values. They store only the non-zero elements along with their indices, saving memory and computation time. Sparse tensors are commonly used in tasks involving sparse data, such as natural language processing.

DataSets: DataSets provide an abstraction for handling large datasets and enable efficient data loading, preprocessing, and batching. They allow for easy iteration over the data during model training or evaluation. For instance, a dataset can represent a collection of images or a sequence of text documents.

Ragged Tensors: Ragged Tensors are used to represent tensors with varying lengths along one or more dimensions. They are suitable for handling data with irregular shapes, such as sequences of different lengths or nested structures. For example, a ragged tensor can represent sentences of varying lengths in a language model.

These data structures form the foundation for representing and manipulating data in TensorFlow. Each structure serves a specific purpose and is used in different contexts to facilitate efficient computation and training of machine learning models.
"""
"""
How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example
"""
"""
TensorFlow Constant:
A TensorFlow constant is a data structure that holds a fixed value throughout the computation. It is immutable, meaning its value cannot be changed once it is defined. Constants are typically used to store fixed values like hyperparameters or input data that remain the same during the execution of the computational graph.

TensorFlow Variable:
A TensorFlow variable, on the other hand, is a mutable data structure that can hold values that are updated during the computation. Variables are typically used to store model parameters that need to be optimized, such as weights and biases in neural networks. Unlike constants, variables can be modified and updated during training or optimization processes.

In summary, TensorFlow constants hold fixed values throughout the computation, while TensorFlow variables are mutable and can be updated during the computation, typically used for model parameters. Constants are immutable and cannot be changed, while variables are mutable and can be optimized or updated during training or optimization processes.
"""
"""
Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.
"""
"""
In TensorFlow, matrix addition, multiplication, and element-wise operations are fundamental mathematical operations that can be performed on tensors. Here's a description of each process:

Matrix Addition:
Matrix addition involves adding two matrices of the same shape element-wise. In TensorFlow, you can perform matrix addition using the tf.add() function or the + operator.

import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix1, matrix2)

# Create a TensorFlow session and run the computation
with tf.Session() as sess:
    output = sess.run(result)
    print(output)  # Output: [[6, 8], [10, 12]]
Matrix Multiplication:
Matrix multiplication involves multiplying two matrices, and the number of columns in the first matrix must match the number of rows in the second matrix. In TensorFlow, you can use the tf.matmul() function to perform matrix multiplication.


import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix1, matrix2)

# Create a TensorFlow session and run the computation
with tf.Session() as sess:
    output = sess.run(result)
    print(output)  # Output: [[19, 22], [43, 50]]

Element-wise Operations:
Element-wise operations are operations performed independently on corresponding elements of two tensors of the same shape. TensorFlow provides various element-wise operations, such as element-wise addition (tf.add()), element-wise subtraction (tf.subtract()), element-wise multiplication (tf.multiply()), element-wise division (tf.divide()), and more.

import tensorflow as tf

# Define two tensors
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

# Perform element-wise addition
add_result = tf.add(tensor1, tensor2)

# Perform element-wise multiplication
mul_result = tf.multiply(tensor1, tensor2)

# Create a TensorFlow session and run the computations
with tf.Session() as sess:
    add_output = sess.run(add_result)
    mul_output = sess.run(mul_result)
    print(add_output)  # Output: [5, 7, 9]
    print(mul_output)  # Output: [4, 10, 18]

"""
"""
Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix A
"""

In [1]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 3.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 80.4 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 43.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 52.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 22.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 72.4 MB/s eta 0:00:00:00:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 66.6 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 14.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 73.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 75.8 MB/s eta 

In [3]:
import tensorflow as tf
# Create a 2x2 matrix with random values from a normal distribution
matrix_A = tf.random.normal(shape=[2, 2])

# Evaluate the matrix A
matrix_A_values = matrix_A.numpy()

print(matrix_A_values)

2023-08-11 10:14:23.532983: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-11 10:14:23.604283: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-11 10:14:23.605651: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-11 10:14:24.801229: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


[[ 0.41294628 -2.5645945 ]
 [ 1.1481975  -0.5910397 ]]


In [4]:
"""
Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix B
"""
import tensorflow as tf

# User-defined dimensions of matrix B
x = 3

# Create a Gaussian matrix B with dimensions x
matrix_B = tf.random.truncated_normal(shape=[x, x])

# Evaluate the matrix B
matrix_B_values = matrix_B.numpy()

print(matrix_B_values)

[[-0.94311404 -1.3893853  -0.62580204]
 [ 0.5263541   1.773253    1.2424884 ]
 [ 0.10845061 -1.1478022  -0.45103768]]


In [5]:
"""
Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values
of matrix C
"""
import tensorflow as tf

# User-defined standard deviation value
std_dev = 0.5

# Create a 2x2 matrix with values drawn from normal distribution
matrix_C = tf.random.normal(shape=[2, 2], mean=2, stddev=std_dev)

# Evaluate the matrix C
matrix_C_values = matrix_C.numpy()

print(matrix_C_values)

[[2.8691144 2.0042288]
 [2.3370662 2.207023 ]]


In [6]:
"""
Perform matrix addition between matrix A and matrix B, and store the result in matrix D
"""
import tensorflow as tf

# User-defined standard deviation value
std_dev = 0.5

# Create a 2x2 matrix with values drawn from normal distribution
matrix_D = tf.random.normal(shape=[2, 2], mean=2, stddev=std_dev)

# Evaluate the matrix C
matrix_D_values = matrix_D.numpy()

print(matrix_D_values)

[[2.2230713 1.3622404]
 [2.5268033 1.706027 ]]


In [7]:
"""
Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
"""
import tensorflow as tf

# Define matrix C and matrix D
matrix_C = tf.constant([[1, 2], [3, 4]])
matrix_D = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
matrix_E = tf.matmul(matrix_C, matrix_D)

# Evaluate the matrix E
matrix_E_values = matrix_E.numpy()

print(matrix_E_values)

[[19 22]
 [43 50]]


In [8]:
"""
Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
function
"""
import tensorflow as tf

# Create a 2x2 matrix with random values from a uniform distribution
matrix_F = tf.random.uniform(shape=[2, 2])

# Evaluate the matrix F
matrix_F_values = matrix_F.numpy()

print(matrix_F_values)

[[0.6370084  0.7258302 ]
 [0.08211458 0.2790619 ]]


In [9]:
"""
Calculate the transpose of matrix F and store the result in matrix Gc
"""
import tensorflow as tf

# Define matrix F
matrix_F = tf.constant([[1, 2], [3, 4]])

# Calculate the transpose of matrix F
matrix_G = tf.transpose(matrix_F)

# Evaluate the matrix G
matrix_G_values = matrix_G.numpy()

print(matrix_G_values)

[[1 3]
 [2 4]]


In [ ]:
"""
Calculate the element wise exponential of matrix F and store the result in matrix H
"""
import tensorflow as tf

# Define matrix F
matrix_F = tf.constant([[1, 2], [3, 4]])

# Calculate the element-wise exponential of matrix F
matrix_H = tf.exp(matrix_F)

# Evaluate the matrix H
matrix_H_values = matrix_H.numpy()

print(matrix_H_values)


In [11]:
"""
 Create a matrix I by concatenating matrix F and matrix G horizontally
"""
import tensorflow as tf

# Define matrix F and matrix G
matrix_F = tf.constant([[1, 2], [3, 4]])
matrix_G = tf.constant([[5, 6], [7, 8]])

# Concatenate matrix F and matrix G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)

# Evaluate the matrix I
matrix_I_values = matrix_I.numpy()

print(matrix_I_values)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
"""
Create a matrix J by concatenating matrix F and matrix H vertically.
"""
import tensorflow as tf

# Define matrix F and matrix H
matrix_F = tf.constant([[1, 2], [3, 4]])
matrix_H = tf.constant([[2.718, 7.389], [20.086, 54.598]])

# Concatenate matrix F and matrix H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)

# Evaluate the matrix J
matrix_J_values = matrix_J.numpy()

print(matrix_J_values)
